enum Exceptions {
    NO_ERRORS,
    EXECUTION_PARAMETERS_ERROR,
    INVALID_CONFIG_NAME_ERROR,
    INVALID_COMMAND_ERROR,
    INVALID_COMMAND_ARGS_ERROR,
    INVALID_WAV_ERROR,
    INVALID_FILENAME_ERROR,
    UNKNOWN_ERROR
};
